[phases.setup]
nixPkgs = ["ruby"]
aptPkgs = ["python3", "python3-pip"]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt --break-system-packages", "bundle install"]

[start]
cmd = "python3 bot.py & ruby myapp.rb"
